name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

jobs:
  test:
    name: OTP ${{matrix.otp}}
    runs-on: 'ubuntu-24.04'
    strategy:
      matrix:
        otp: ['27', '26', '25']
        rebar3: ['3.24.0']
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - uses: actions/cache@v4
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ matrix.otp-version }}-${{ hashFiles(format('rebar.lock')) }}-1
          restore-keys: ${{ runner.os }}-build-${{ matrix.otp-version }}-1
      - run: rebar3 compile
      - run: rebar3 lint
      - run: rebar3 fmt --check
      - run: rebar3 xref
      - run: rebar3 ex_doc
      - run: rebar3 eunit
      - run: rebar3 ct
      - run: rebar3 dialyzer
      - run: rebar3 do cover, covertool generate
      - name: Upload code coverage
        uses: codecov/codecov-action@v5
        with:
          files: _build/test/covertool/*.covertool.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
